############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Team"
url = "authors/"
weight=2

[[main]]
name = "Blog"
url = "blog/"
weight = 3

#[[main]]
#name = "About"
#url = "about/"
#weight = 2

# [[main]]
# weight = 4
# name = "More"
# hasChildren = true

# [[main]]
# parent = "More"
# name = "Contact"
# url = "contact/"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "categories/"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "404/"

# footer menu
# [[footer]]
# name = "About"
# url = "about/"
# weight = 1

[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Team"
url = "authors/"
weight = 2

[[footer]]
name = "Blog"
url = "blog/"
weight = 3
