############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
weight = 4
name = "More"
hasChildren = true

[[main]]
parent = "More"
name = "Blog"
url = "blog/"

[[main]]
parent = "More"
name = "Contact"
url = "contact/"

[[main]]
name = "Team"
url = "authors/"
weight=3

[[main]]
parent = "More"
name = "Categories"
url = "categories/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Team"
url = "authors/"
weight = 1

