############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Team"
url = "authors/"
weight=3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

#[[main]]
#name = "About"
#url = "about/"
#weight = 2

# [[main]]
# name = "Solutions"
# hasChildren = true
# weight = 2

# [[main]]
# parent = "Solutions"
# name = "Observability"
# url = "/observability"
# weight = 1

# [[main]]
# parent = "Solutions"
# name = "Linux Software Development"
# url = "/linux-software-development"
# weight = 2

# [[main]]
# parent = "Solutions"
# name = "Algorithm Optimization"
# url = "/algorithm-optimization"
# weight = 3

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "404/"

# footer menu
# [[footer]]
# name = "About"
# url = "about/"
# weight = 1

[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Team"
url = "authors/"
weight = 2

[[footer]]
name = "Blog"
url = "blog/"
weight = 3
