############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
weight = 4
name = "Pages"
hasChildren = true

[[main]]
parent = "Pages"
name = "Blog"
url = "blog/"

[[main]]
parent = "Pages"
name = "Contact"
url = "contact/"

[[main]]
name = "Team"
url = "authors/"
weight=3

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "categories/"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "404/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Elements"
url = "elements/"
weight = 2